{"created": 1739542922.609096, "duration": 1.1209831237792969, "exitcode": 1, "root": "/Users/luckylundy/Documents/\u4f1a\u8b70\u8b70\u4e8b\u9332\u81ea\u52d5\u751f\u6210\u30a2\u30d5\u309a\u30ea/backend", "environment": {}, "summary": {"failed": 15, "passed": 5, "total": 20, "collected": 20}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "tests", "type": "Package"}]}, {"nodeid": "tests/test_crud.py", "outcome": "passed", "result": [{"nodeid": "tests/test_crud.py::test_create_meeting_crud", "type": "Function", "lineno": 5}, {"nodeid": "tests/test_crud.py::test_get_meetings_crud", "type": "Function", "lineno": 21}, {"nodeid": "tests/test_crud.py::test_create_task_crud", "type": "Function", "lineno": 39}, {"nodeid": "tests/test_crud.py::test_get_tasks_by_meeting_crud", "type": "Function", "lineno": 66}, {"nodeid": "tests/test_crud.py::test_update_task_crud", "type": "Function", "lineno": 93}]}, {"nodeid": "tests/test_error_cases.py::TestClient", "outcome": "passed", "result": []}, {"nodeid": "tests/test_error_cases.py", "outcome": "passed", "result": [{"nodeid": "tests/test_error_cases.py::TestClient", "type": "Class"}, {"nodeid": "tests/test_error_cases.py::test_meeting_not_found", "type": "Function", "lineno": 6}, {"nodeid": "tests/test_error_cases.py::test_invalid_meeting_data", "type": "Function", "lineno": 10}, {"nodeid": "tests/test_error_cases.py::test_delete_nonexistent_meeting", "type": "Function", "lineno": 21}, {"nodeid": "tests/test_error_cases.py::test_invalid_task_status", "type": "Function", "lineno": 25}]}, {"nodeid": "tests/test_meetings.py::TestClient", "outcome": "passed", "result": []}, {"nodeid": "tests/test_meetings.py::TestMeetings", "outcome": "passed", "result": [{"nodeid": "tests/test_meetings.py::TestMeetings::test_create_meeting", "type": "Function", "lineno": 24}, {"nodeid": "tests/test_meetings.py::TestMeetings::test_create_meeting_invalid_time", "type": "Function", "lineno": 31}, {"nodeid": "tests/test_meetings.py::TestMeetings::test_create_meeting_end_before_start", "type": "Function", "lineno": 37}, {"nodeid": "tests/test_meetings.py::TestMeetings::test_get_meetings", "type": "Function", "lineno": 44}, {"nodeid": "tests/test_meetings.py::TestMeetings::test_get_meeting_by_id", "type": "Function", "lineno": 54}, {"nodeid": "tests/test_meetings.py::TestMeetings::test_update_meeting", "type": "Function", "lineno": 64}, {"nodeid": "tests/test_meetings.py::TestMeetings::test_delete_meeting", "type": "Function", "lineno": 76}]}, {"nodeid": "tests/test_meetings.py::TestTasks", "outcome": "passed", "result": [{"nodeid": "tests/test_meetings.py::TestTasks::test_create_task", "type": "Function", "lineno": 88}, {"nodeid": "tests/test_meetings.py::TestTasks::test_get_meeting_tasks", "type": "Function", "lineno": 105}]}, {"nodeid": "tests/test_meetings.py", "outcome": "passed", "result": [{"nodeid": "tests/test_meetings.py::TestClient", "type": "Class"}, {"nodeid": "tests/test_meetings.py::TestMeetings", "type": "Class"}, {"nodeid": "tests/test_meetings.py::TestTasks", "type": "Class"}]}, {"nodeid": "tests/test_schemas.py", "outcome": "passed", "result": [{"nodeid": "tests/test_schemas.py::test_meeting_create_validation", "type": "Function", "lineno": 5}, {"nodeid": "tests/test_schemas.py::test_task_create_validation", "type": "Function", "lineno": 30}]}, {"nodeid": "tests", "outcome": "passed", "result": [{"nodeid": "tests/test_crud.py", "type": "Module"}, {"nodeid": "tests/test_error_cases.py", "type": "Module"}, {"nodeid": "tests/test_meetings.py", "type": "Module"}, {"nodeid": "tests/test_schemas.py", "type": "Module"}]}], "tests": [{"nodeid": "tests/test_crud.py::test_create_meeting_crud", "lineno": 5, "outcome": "failed", "keywords": ["test_create_meeting_crud", "test_crud.py", "tests", "backend", ""], "setup": {"duration": 0.024366746999999744, "outcome": "passed"}, "call": {"duration": 0.0004073870000000923, "outcome": "failed", "crash": {"path": "/Users/luckylundy/Documents/\u4f1a\u8b70\u8b70\u4e8b\u9332\u81ea\u52d5\u751f\u6210\u30a2\u30d5\u309a\u30ea/backend/app/schemas.py", "lineno": 85, "message": "app.exceptions.DateValidationError: \u7121\u52b9\u306a\u65e5\u4ed8\u5f62\u5f0f\u3067\u3059\u3002\u6b63\u3057\u3044\u65e5\u4ed8\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3002"}, "traceback": [{"path": "tests/test_crud.py", "lineno": 7, "message": ""}, {"path": "app/schemas.py", "lineno": 85, "message": "DateValidationError"}], "longrepr": "db = <sqlalchemy.orm.session.Session object at 0x10e61ae20>\n\n    def test_create_meeting_crud(db):\n>       meeting_data = MeetingCreate(\n            title=\"\u30c6\u30b9\u30c8\u4f1a\u8b70\",\n            date=\"2025-02-14T10:00:00\",\n            start_time=\"10:00\",\n            end_time=\"11:00\",\n            participants=[\"\u7530\u4e2d\", \"\u9234\u6728\"],\n            audio_file_path=None,\n            transcript=None,\n            summary=None\n        )\n\ntests/test_crud.py:7: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncls = <class 'app.schemas.MeetingCreate'>\nv = datetime.datetime(2025, 2, 14, 10, 0)\n\n    @field_validator('date')\n    @classmethod\n    def validate_meeting_date(cls, v):\n        if v < datetime.now():\n>           raise DateValidationError()\nE           app.exceptions.DateValidationError: \u7121\u52b9\u306a\u65e5\u4ed8\u5f62\u5f0f\u3067\u3059\u3002\u6b63\u3057\u3044\u65e5\u4ed8\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3002\n\napp/schemas.py:85: DateValidationError"}, "teardown": {"duration": 0.007854028000000124, "outcome": "passed"}}, {"nodeid": "tests/test_crud.py::test_get_meetings_crud", "lineno": 21, "outcome": "failed", "keywords": ["test_get_meetings_crud", "test_crud.py", "tests", "backend", ""], "setup": {"duration": 0.021159209999999984, "outcome": "passed"}, "call": {"duration": 0.0003411780000002196, "outcome": "failed", "crash": {"path": "/Users/luckylundy/Documents/\u4f1a\u8b70\u8b70\u4e8b\u9332\u81ea\u52d5\u751f\u6210\u30a2\u30d5\u309a\u30ea/backend/app/schemas.py", "lineno": 85, "message": "app.exceptions.DateValidationError: \u7121\u52b9\u306a\u65e5\u4ed8\u5f62\u5f0f\u3067\u3059\u3002\u6b63\u3057\u3044\u65e5\u4ed8\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3002"}, "traceback": [{"path": "tests/test_crud.py", "lineno": 24, "message": ""}, {"path": "app/schemas.py", "lineno": 85, "message": "DateValidationError"}], "longrepr": "db = <sqlalchemy.orm.session.Session object at 0x10e6c1ca0>\n\n    def test_get_meetings_crud(db):\n        # \u30c6\u30b9\u30c8\u30c7\u30fc\u30bf\u3092\u4f5c\u6210\n>       meeting_data = MeetingCreate(\n            title=\"\u30c6\u30b9\u30c8\u4f1a\u8b701\",\n            date=\"2025-02-14T10:00:00\",\n            start_time=\"10:00\",\n            end_time=\"11:00\",\n            participants=[\"\u7530\u4e2d\"],\n            audio_file_path=None,\n            transcript=None,\n            summary=None\n        )\n\ntests/test_crud.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncls = <class 'app.schemas.MeetingCreate'>\nv = datetime.datetime(2025, 2, 14, 10, 0)\n\n    @field_validator('date')\n    @classmethod\n    def validate_meeting_date(cls, v):\n        if v < datetime.now():\n>           raise DateValidationError()\nE           app.exceptions.DateValidationError: \u7121\u52b9\u306a\u65e5\u4ed8\u5f62\u5f0f\u3067\u3059\u3002\u6b63\u3057\u3044\u65e5\u4ed8\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3002\n\napp/schemas.py:85: DateValidationError"}, "teardown": {"duration": 0.007193307000000093, "outcome": "passed"}}, {"nodeid": "tests/test_crud.py::test_create_task_crud", "lineno": 39, "outcome": "failed", "keywords": ["test_create_task_crud", "test_crud.py", "tests", "backend", ""], "setup": {"duration": 0.022809462000000114, "outcome": "passed"}, "call": {"duration": 0.001213125000000037, "outcome": "failed", "crash": {"path": "/Users/luckylundy/Documents/\u4f1a\u8b70\u8b70\u4e8b\u9332\u81ea\u52d5\u751f\u6210\u30a2\u30d5\u309a\u30ea/backend/app/schemas.py", "lineno": 85, "message": "app.exceptions.DateValidationError: \u7121\u52b9\u306a\u65e5\u4ed8\u5f62\u5f0f\u3067\u3059\u3002\u6b63\u3057\u3044\u65e5\u4ed8\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3002"}, "traceback": [{"path": "tests/test_crud.py", "lineno": 42, "message": ""}, {"path": "app/schemas.py", "lineno": 85, "message": "DateValidationError"}], "longrepr": "db = <sqlalchemy.orm.session.Session object at 0x10e63be80>\n\n    def test_create_task_crud(db):\n        # \u307e\u305a\u4f1a\u8b70\u3092\u4f5c\u6210\n>       meeting_data = MeetingCreate(\n            title=\"\u30c6\u30b9\u30c8\u4f1a\u8b70\",\n            date=\"2025-02-14T10:00:00\",\n            start_time=\"10:00\",\n            end_time=\"11:00\",\n            participants=[\"\u7530\u4e2d\"],\n            audio_file_path=None,\n            transcript=None,\n            summary=None\n        )\n\ntests/test_crud.py:42: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncls = <class 'app.schemas.MeetingCreate'>\nv = datetime.datetime(2025, 2, 14, 10, 0)\n\n    @field_validator('date')\n    @classmethod\n    def validate_meeting_date(cls, v):\n        if v < datetime.now():\n>           raise DateValidationError()\nE           app.exceptions.DateValidationError: \u7121\u52b9\u306a\u65e5\u4ed8\u5f62\u5f0f\u3067\u3059\u3002\u6b63\u3057\u3044\u65e5\u4ed8\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3002\n\napp/schemas.py:85: DateValidationError"}, "teardown": {"duration": 0.003966462999999809, "outcome": "passed"}}, {"nodeid": "tests/test_crud.py::test_get_tasks_by_meeting_crud", "lineno": 66, "outcome": "failed", "keywords": ["test_get_tasks_by_meeting_crud", "test_crud.py", "tests", "backend", ""], "setup": {"duration": 0.018591905000000075, "outcome": "passed"}, "call": {"duration": 0.0003132859999999127, "outcome": "failed", "crash": {"path": "/Users/luckylundy/Documents/\u4f1a\u8b70\u8b70\u4e8b\u9332\u81ea\u52d5\u751f\u6210\u30a2\u30d5\u309a\u30ea/backend/app/schemas.py", "lineno": 85, "message": "app.exceptions.DateValidationError: \u7121\u52b9\u306a\u65e5\u4ed8\u5f62\u5f0f\u3067\u3059\u3002\u6b63\u3057\u3044\u65e5\u4ed8\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3002"}, "traceback": [{"path": "tests/test_crud.py", "lineno": 69, "message": ""}, {"path": "app/schemas.py", "lineno": 85, "message": "DateValidationError"}], "longrepr": "db = <sqlalchemy.orm.session.Session object at 0x10e62bcd0>\n\n    def test_get_tasks_by_meeting_crud(db):\n        # \u4f1a\u8b70\u3068\u30bf\u30b9\u30af\u3092\u4f5c\u6210\n>       meeting_data = MeetingCreate(\n            title=\"\u30c6\u30b9\u30c8\u4f1a\u8b70\",\n            date=\"2025-02-14T10:00:00\",\n            start_time=\"10:00\",\n            end_time=\"11:00\",\n            participants=[\"\u7530\u4e2d\"],\n            audio_file_path=None,\n            transcript=None,\n            summary=None\n        )\n\ntests/test_crud.py:69: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncls = <class 'app.schemas.MeetingCreate'>\nv = datetime.datetime(2025, 2, 14, 10, 0)\n\n    @field_validator('date')\n    @classmethod\n    def validate_meeting_date(cls, v):\n        if v < datetime.now():\n>           raise DateValidationError()\nE           app.exceptions.DateValidationError: \u7121\u52b9\u306a\u65e5\u4ed8\u5f62\u5f0f\u3067\u3059\u3002\u6b63\u3057\u3044\u65e5\u4ed8\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3002\n\napp/schemas.py:85: DateValidationError"}, "teardown": {"duration": 0.004203104000000124, "outcome": "passed"}}, {"nodeid": "tests/test_crud.py::test_update_task_crud", "lineno": 93, "outcome": "failed", "keywords": ["test_update_task_crud", "test_crud.py", "tests", "backend", ""], "setup": {"duration": 0.017397125000000013, "outcome": "passed"}, "call": {"duration": 0.00046039199999992064, "outcome": "failed", "crash": {"path": "/Users/luckylundy/Documents/\u4f1a\u8b70\u8b70\u4e8b\u9332\u81ea\u52d5\u751f\u6210\u30a2\u30d5\u309a\u30ea/backend/app/schemas.py", "lineno": 85, "message": "app.exceptions.DateValidationError: \u7121\u52b9\u306a\u65e5\u4ed8\u5f62\u5f0f\u3067\u3059\u3002\u6b63\u3057\u3044\u65e5\u4ed8\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3002"}, "traceback": [{"path": "tests/test_crud.py", "lineno": 96, "message": ""}, {"path": "app/schemas.py", "lineno": 85, "message": "DateValidationError"}], "longrepr": "db = <sqlalchemy.orm.session.Session object at 0x10e6e7d00>\n\n    def test_update_task_crud(db):\n        # \u4f1a\u8b70\u3068\u30bf\u30b9\u30af\u3092\u4f5c\u6210\n>       meeting_data = MeetingCreate(\n            title=\"\u30c6\u30b9\u30c8\u4f1a\u8b70\",\n            date=\"2025-02-14T10:00:00\",\n            start_time=\"10:00\",\n            end_time=\"11:00\",\n            participants=[\"\u7530\u4e2d\"],\n            audio_file_path=None,\n            transcript=None,\n            summary=None\n        )\n\ntests/test_crud.py:96: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncls = <class 'app.schemas.MeetingCreate'>\nv = datetime.datetime(2025, 2, 14, 10, 0)\n\n    @field_validator('date')\n    @classmethod\n    def validate_meeting_date(cls, v):\n        if v < datetime.now():\n>           raise DateValidationError()\nE           app.exceptions.DateValidationError: \u7121\u52b9\u306a\u65e5\u4ed8\u5f62\u5f0f\u3067\u3059\u3002\u6b63\u3057\u3044\u65e5\u4ed8\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3002\n\napp/schemas.py:85: DateValidationError"}, "teardown": {"duration": 0.005068956000000124, "outcome": "passed"}}, {"nodeid": "tests/test_error_cases.py::test_meeting_not_found", "lineno": 6, "outcome": "passed", "keywords": ["test_meeting_not_found", "test_error_cases.py", "tests", "backend", ""], "setup": {"duration": 0.05900526199999989, "outcome": "passed"}, "call": {"duration": 0.020058391000000064, "outcome": "passed"}, "teardown": {"duration": 0.011557045999999627, "outcome": "passed"}}, {"nodeid": "tests/test_error_cases.py::test_invalid_meeting_data", "lineno": 10, "outcome": "passed", "keywords": ["test_invalid_meeting_data", "test_error_cases.py", "tests", "backend", ""], "setup": {"duration": 0.0294128739999997, "outcome": "passed"}, "call": {"duration": 0.009071764000000204, "outcome": "passed"}, "teardown": {"duration": 0.012367719000000221, "outcome": "passed"}}, {"nodeid": "tests/test_error_cases.py::test_delete_nonexistent_meeting", "lineno": 21, "outcome": "passed", "keywords": ["test_delete_nonexistent_meeting", "test_error_cases.py", "tests", "backend", ""], "setup": {"duration": 0.021347824000000237, "outcome": "passed"}, "call": {"duration": 0.00556402399999989, "outcome": "passed"}, "teardown": {"duration": 0.01868059799999955, "outcome": "passed"}}, {"nodeid": "tests/test_error_cases.py::test_invalid_task_status", "lineno": 25, "outcome": "failed", "keywords": ["test_invalid_task_status", "test_error_cases.py", "tests", "backend", ""], "setup": {"duration": 0.021109880000000025, "outcome": "passed"}, "call": {"duration": 0.004903935999999831, "outcome": "failed", "crash": {"path": "/Users/luckylundy/Documents/\u4f1a\u8b70\u8b70\u4e8b\u9332\u81ea\u52d5\u751f\u6210\u30a2\u30d5\u309a\u30ea/backend/tests/test_error_cases.py", "lineno": 39, "message": "KeyError: 'id'"}, "traceback": [{"path": "tests/test_error_cases.py", "lineno": 39, "message": "KeyError"}], "longrepr": "client = <starlette.testclient.TestClient object at 0x10e670790>\n\n    def test_invalid_task_status(client):\n        # \u307e\u305a\u4f1a\u8b70\u3092\u4f5c\u6210\n        meeting_data = {\n            \"title\": \"\u30c6\u30b9\u30c8\u4f1a\u8b70\",\n            \"date\": \"2025-02-14T10:00:00\",\n            \"start_time\": \"10:00\",\n            \"end_time\": \"11:00\",\n            \"participants\": [\"\u7530\u4e2d\"],\n            \"audio_file_path\": None,\n            \"transcript\": None,\n            \"summary\": None\n        }\n        create_response = client.post(\"/api/meetings\", json=meeting_data)\n>       meeting_id = create_response.json()[\"id\"]\nE       KeyError: 'id'\n\ntests/test_error_cases.py:39: KeyError"}, "teardown": {"duration": 0.010469810000000024, "outcome": "passed"}}, {"nodeid": "tests/test_meetings.py::TestMeetings::test_create_meeting", "lineno": 24, "outcome": "failed", "keywords": ["test_create_meeting", "TestMeetings", "test_meetings.py", "tests", "backend", ""], "setup": {"duration": 0.02097522800000018, "outcome": "passed"}, "call": {"duration": 0.0038731520000006014, "outcome": "failed", "crash": {"path": "/Users/luckylundy/Documents/\u4f1a\u8b70\u8b70\u4e8b\u9332\u81ea\u52d5\u751f\u6210\u30a2\u30d5\u309a\u30ea/backend/tests/test_meetings.py", "lineno": 27, "message": "assert 422 == 200\n +  where 422 = <Response [422 Unprocessable Entity]>.status_code"}, "traceback": [{"path": "tests/test_meetings.py", "lineno": 27, "message": "AssertionError"}], "longrepr": "self = <tests.test_meetings.TestMeetings object at 0x10e681e80>\nclient = <starlette.testclient.TestClient object at 0x10e8272b0>\n\n    def test_create_meeting(self, client):\n        response = client.post(\"/api/meetings\", json=valid_meeting_data)\n>       assert response.status_code == 200\nE       assert 422 == 200\nE        +  where 422 = <Response [422 Unprocessable Entity]>.status_code\n\ntests/test_meetings.py:27: AssertionError"}, "teardown": {"duration": 0.010199013000000257, "outcome": "passed"}}, {"nodeid": "tests/test_meetings.py::TestMeetings::test_create_meeting_invalid_time", "lineno": 31, "outcome": "passed", "keywords": ["test_create_meeting_invalid_time", "TestMeetings", "test_meetings.py", "tests", "backend", ""], "setup": {"duration": 0.020795900999999617, "outcome": "passed"}, "call": {"duration": 0.0031363829999992987, "outcome": "passed"}, "teardown": {"duration": 0.010531592000000423, "outcome": "passed"}}, {"nodeid": "tests/test_meetings.py::TestMeetings::test_create_meeting_end_before_start", "lineno": 37, "outcome": "passed", "keywords": ["test_create_meeting_end_before_start", "TestMeetings", "test_meetings.py", "tests", "backend", ""], "setup": {"duration": 0.024981844999999225, "outcome": "passed"}, "call": {"duration": 0.008635943999999895, "outcome": "passed"}, "teardown": {"duration": 0.008294796000000382, "outcome": "passed"}}, {"nodeid": "tests/test_meetings.py::TestMeetings::test_get_meetings", "lineno": 44, "outcome": "failed", "keywords": ["test_get_meetings", "TestMeetings", "test_meetings.py", "tests", "backend", ""], "setup": {"duration": 0.022122551999999907, "outcome": "passed"}, "call": {"duration": 0.008345324000000431, "outcome": "failed", "crash": {"path": "/Users/luckylundy/Documents/\u4f1a\u8b70\u8b70\u4e8b\u9332\u81ea\u52d5\u751f\u6210\u30a2\u30d5\u309a\u30ea/backend/tests/test_meetings.py", "lineno": 53, "message": "assert 0 > 0\n +  where 0 = len([])"}, "traceback": [{"path": "tests/test_meetings.py", "lineno": 53, "message": "AssertionError"}], "longrepr": "self = <tests.test_meetings.TestMeetings object at 0x10e681340>\nclient = <starlette.testclient.TestClient object at 0x10e7cdc40>\n\n    def test_get_meetings(self, client):\n        # \u307e\u305a\u4f1a\u8b70\u3092\u4f5c\u6210\n        client.post(\"/api/meetings\", json=valid_meeting_data)\n        # \u4f1a\u8b70\u4e00\u89a7\u3092\u53d6\u5f97\n        response = client.get(\"/api/meetings/\")\n        assert response.status_code == 200\n        data = response.json()\n        assert isinstance(data, list)\n>       assert len(data) > 0\nE       assert 0 > 0\nE        +  where 0 = len([])\n\ntests/test_meetings.py:53: AssertionError"}, "teardown": {"duration": 0.00872926700000054, "outcome": "passed"}}, {"nodeid": "tests/test_meetings.py::TestMeetings::test_get_meeting_by_id", "lineno": 54, "outcome": "failed", "keywords": ["test_get_meeting_by_id", "TestMeetings", "test_meetings.py", "tests", "backend", ""], "setup": {"duration": 0.013359663000000133, "outcome": "passed"}, "call": {"duration": 0.0030930250000000825, "outcome": "failed", "crash": {"path": "/Users/luckylundy/Documents/\u4f1a\u8b70\u8b70\u4e8b\u9332\u81ea\u52d5\u751f\u6210\u30a2\u30d5\u309a\u30ea/backend/tests/test_meetings.py", "lineno": 58, "message": "KeyError: 'id'"}, "traceback": [{"path": "tests/test_meetings.py", "lineno": 58, "message": "KeyError"}], "longrepr": "self = <tests.test_meetings.TestMeetings object at 0x10e61af10>\nclient = <starlette.testclient.TestClient object at 0x10e8109d0>\n\n    def test_get_meeting_by_id(self, client):\n        # \u307e\u305a\u4f1a\u8b70\u3092\u4f5c\u6210\n        create_response = client.post(\"/api/meetings\", json=valid_meeting_data)\n>       meeting_id = create_response.json()[\"id\"]\nE       KeyError: 'id'\n\ntests/test_meetings.py:58: KeyError"}, "teardown": {"duration": 0.008702064000000398, "outcome": "passed"}}, {"nodeid": "tests/test_meetings.py::TestMeetings::test_update_meeting", "lineno": 64, "outcome": "failed", "keywords": ["test_update_meeting", "TestMeetings", "test_meetings.py", "tests", "backend", ""], "setup": {"duration": 0.030670413000000174, "outcome": "passed"}, "call": {"duration": 0.003581996999999504, "outcome": "failed", "crash": {"path": "/Users/luckylundy/Documents/\u4f1a\u8b70\u8b70\u4e8b\u9332\u81ea\u52d5\u751f\u6210\u30a2\u30d5\u309a\u30ea/backend/tests/test_meetings.py", "lineno": 68, "message": "KeyError: 'id'"}, "traceback": [{"path": "tests/test_meetings.py", "lineno": 68, "message": "KeyError"}], "longrepr": "self = <tests.test_meetings.TestMeetings object at 0x10e61a700>\nclient = <starlette.testclient.TestClient object at 0x10e82eb50>\n\n    def test_update_meeting(self, client):\n        # \u307e\u305a\u4f1a\u8b70\u3092\u4f5c\u6210\n        create_response = client.post(\"/api/meetings\", json=valid_meeting_data)\n>       meeting_id = create_response.json()[\"id\"]\nE       KeyError: 'id'\n\ntests/test_meetings.py:68: KeyError"}, "teardown": {"duration": 0.008343808999999425, "outcome": "passed"}}, {"nodeid": "tests/test_meetings.py::TestMeetings::test_delete_meeting", "lineno": 76, "outcome": "failed", "keywords": ["test_delete_meeting", "TestMeetings", "test_meetings.py", "tests", "backend", ""], "setup": {"duration": 0.02594376700000023, "outcome": "passed"}, "call": {"duration": 0.003856284000000265, "outcome": "failed", "crash": {"path": "/Users/luckylundy/Documents/\u4f1a\u8b70\u8b70\u4e8b\u9332\u81ea\u52d5\u751f\u6210\u30a2\u30d5\u309a\u30ea/backend/tests/test_meetings.py", "lineno": 80, "message": "KeyError: 'id'"}, "traceback": [{"path": "tests/test_meetings.py", "lineno": 80, "message": "KeyError"}], "longrepr": "self = <tests.test_meetings.TestMeetings object at 0x10e668220>\nclient = <starlette.testclient.TestClient object at 0x10e842190>\n\n    def test_delete_meeting(self, client):\n        # \u307e\u305a\u4f1a\u8b70\u3092\u4f5c\u6210\n        create_response = client.post(\"/api/meetings\", json=valid_meeting_data)\n>       meeting_id = create_response.json()[\"id\"]\nE       KeyError: 'id'\n\ntests/test_meetings.py:80: KeyError"}, "teardown": {"duration": 0.012323714999999957, "outcome": "passed"}}, {"nodeid": "tests/test_meetings.py::TestTasks::test_create_task", "lineno": 88, "outcome": "failed", "keywords": ["test_create_task", "TestTasks", "test_meetings.py", "tests", "backend", ""], "setup": {"duration": 0.03229985300000049, "outcome": "passed"}, "call": {"duration": 0.003920057999999393, "outcome": "failed", "crash": {"path": "/Users/luckylundy/Documents/\u4f1a\u8b70\u8b70\u4e8b\u9332\u81ea\u52d5\u751f\u6210\u30a2\u30d5\u309a\u30ea/backend/tests/test_meetings.py", "lineno": 92, "message": "KeyError: 'id'"}, "traceback": [{"path": "tests/test_meetings.py", "lineno": 92, "message": "KeyError"}], "longrepr": "self = <tests.test_meetings.TestTasks object at 0x10e668370>\nclient = <starlette.testclient.TestClient object at 0x10e8719d0>\n\n    def test_create_task(self, client):\n        # \u307e\u305a\u4f1a\u8b70\u3092\u4f5c\u6210\n        create_meeting_response = client.post(\"/api/meetings\", json=valid_meeting_data)\n>       meeting_id = create_meeting_response.json()[\"id\"]\nE       KeyError: 'id'\n\ntests/test_meetings.py:92: KeyError"}, "teardown": {"duration": 0.020780779999999943, "outcome": "passed"}}, {"nodeid": "tests/test_meetings.py::TestTasks::test_get_meeting_tasks", "lineno": 105, "outcome": "failed", "keywords": ["test_get_meeting_tasks", "TestTasks", "test_meetings.py", "tests", "backend", ""], "setup": {"duration": 0.03430011099999941, "outcome": "passed"}, "call": {"duration": 0.0036495470000001973, "outcome": "failed", "crash": {"path": "/Users/luckylundy/Documents/\u4f1a\u8b70\u8b70\u4e8b\u9332\u81ea\u52d5\u751f\u6210\u30a2\u30d5\u309a\u30ea/backend/tests/test_meetings.py", "lineno": 109, "message": "KeyError: 'id'"}, "traceback": [{"path": "tests/test_meetings.py", "lineno": 109, "message": "KeyError"}], "longrepr": "self = <tests.test_meetings.TestTasks object at 0x10e6686d0>\nclient = <starlette.testclient.TestClient object at 0x10e855400>\n\n    def test_get_meeting_tasks(self, client):\n        # \u307e\u305a\u4f1a\u8b70\u3068\u30bf\u30b9\u30af\u3092\u4f5c\u6210\n        create_meeting_response = client.post(\"/api/meetings\", json=valid_meeting_data)\n>       meeting_id = create_meeting_response.json()[\"id\"]\nE       KeyError: 'id'\n\ntests/test_meetings.py:109: KeyError"}, "teardown": {"duration": 0.03041591600000082, "outcome": "passed"}}, {"nodeid": "tests/test_schemas.py::test_meeting_create_validation", "lineno": 5, "outcome": "failed", "keywords": ["test_meeting_create_validation", "test_schemas.py", "tests", "backend", ""], "setup": {"duration": 0.000450552000000215, "outcome": "passed"}, "call": {"duration": 0.00033209800000033596, "outcome": "failed", "crash": {"path": "/Users/luckylundy/Documents/\u4f1a\u8b70\u8b70\u4e8b\u9332\u81ea\u52d5\u751f\u6210\u30a2\u30d5\u309a\u30ea/backend/app/schemas.py", "lineno": 85, "message": "app.exceptions.DateValidationError: \u7121\u52b9\u306a\u65e5\u4ed8\u5f62\u5f0f\u3067\u3059\u3002\u6b63\u3057\u3044\u65e5\u4ed8\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3002"}, "traceback": [{"path": "tests/test_schemas.py", "lineno": 18, "message": ""}, {"path": "app/schemas.py", "lineno": 85, "message": "DateValidationError"}], "longrepr": "def test_meeting_create_validation():\n        # \u6b63\u5e38\u306a\u30b1\u30fc\u30b9\n        meeting_data = {\n            \"title\": \"\u30c6\u30b9\u30c8\u4f1a\u8b70\",\n            \"date\": \"2025-02-14T10:00:00\",\n            \"start_time\": \"10:00\",\n            \"end_time\": \"11:00\",\n            \"participants\": [\"\u7530\u4e2d\", \"\u9234\u6728\"],\n            \"audio_file_path\": None,\n            \"transcript\": None,\n            \"summary\": None\n        }\n>       meeting = MeetingCreate(**meeting_data)\n\ntests/test_schemas.py:18: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncls = <class 'app.schemas.MeetingCreate'>\nv = datetime.datetime(2025, 2, 14, 10, 0)\n\n    @field_validator('date')\n    @classmethod\n    def validate_meeting_date(cls, v):\n        if v < datetime.now():\n>           raise DateValidationError()\nE           app.exceptions.DateValidationError: \u7121\u52b9\u306a\u65e5\u4ed8\u5f62\u5f0f\u3067\u3059\u3002\u6b63\u3057\u3044\u65e5\u4ed8\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044\u3002\n\napp/schemas.py:85: DateValidationError"}, "teardown": {"duration": 0.00028511200000025383, "outcome": "passed"}}, {"nodeid": "tests/test_schemas.py::test_task_create_validation", "lineno": 30, "outcome": "failed", "keywords": ["test_task_create_validation", "test_schemas.py", "tests", "backend", ""], "setup": {"duration": 0.00031640899999985095, "outcome": "passed"}, "call": {"duration": 0.0010514989999999003, "outcome": "failed", "crash": {"path": "/Users/luckylundy/Documents/\u4f1a\u8b70\u8b70\u4e8b\u9332\u81ea\u52d5\u751f\u6210\u30a2\u30d5\u309a\u30ea/backend/tests/test_schemas.py", "lineno": 39, "message": "pydantic_core._pydantic_core.ValidationError: 1 validation error for TaskCreate\nassignee\n  String should match pattern '^[a-zA-Z0-9_-]+$' [type=string_pattern_mismatch, input_value='\u7530\u4e2d', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.10/v/string_pattern_mismatch"}, "traceback": [{"path": "tests/test_schemas.py", "lineno": 39, "message": "ValidationError"}], "longrepr": "def test_task_create_validation():\n        # \u6b63\u5e38\u306a\u30b1\u30fc\u30b9\n        task_data = {\n            \"content\": \"\u30c6\u30b9\u30c8\u30bf\u30b9\u30af\",\n            \"assignee\": \"\u7530\u4e2d\",\n            \"due_date\": \"2025-02-15T10:00:00\",\n            \"status\": \"pending\"\n        }\n>       task = TaskCreate(**task_data)\nE       pydantic_core._pydantic_core.ValidationError: 1 validation error for TaskCreate\nE       assignee\nE         String should match pattern '^[a-zA-Z0-9_-]+$' [type=string_pattern_mismatch, input_value='\u7530\u4e2d', input_type=str]\nE           For further information visit https://errors.pydantic.dev/2.10/v/string_pattern_mismatch\n\ntests/test_schemas.py:39: ValidationError"}, "teardown": {"duration": 0.0003818159999999793, "outcome": "passed"}}], "warnings": [{"message": "The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)", "category": "MovedIn20Warning", "when": "config", "filename": "/Users/luckylundy/Documents/\u4f1a\u8b70\u8b70\u4e8b\u9332\u81ea\u52d5\u751f\u6210\u30a2\u30d5\u309a\u30ea/backend/app/database.py", "lineno": 17}, {"message": "Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.10/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/Users/luckylundy/Documents/\u4f1a\u8b70\u8b70\u4e8b\u9332\u81ea\u52d5\u751f\u6210\u30a2\u30d5\u309a\u30ea/backend/.venv/lib/python3.9/site-packages/pydantic/_internal/_config.py", "lineno": 295}, {"message": "Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.10/migration/", "category": "PydanticDeprecatedSince20", "when": "config", "filename": "/Users/luckylundy/Documents/\u4f1a\u8b70\u8b70\u4e8b\u9332\u81ea\u52d5\u751f\u6210\u30a2\u30d5\u309a\u30ea/backend/.venv/lib/python3.9/site-packages/pydantic/_internal/_config.py", "lineno": 295}]}